version: "3.8"

services:
  web:
    depends_on: 
      - api
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8002
    volumes:
      - ./frontend:/app

  api:
    depends_on: 
      - db
    build: ./backend
    ports: 
      - "8002:8002"
    environment: 
      DB_URL: mongodb://db:27017/ToDoList_app
    volumes:
      - ./backend:/app

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
